config/routes.rb
Rails.application.routes.draw do
  resources :categories
   # delete '/products/:id', to: 'products#destroy'
   # patch '/products/:id', to: 'products#update'
   # post '/products', to: 'products#create'
   # get '/products/new', to: 'products#new', as: :new_product # ese as: :new_product es el helper para no tener que colocar la URL  (lo maneja el controlador en produicts_controller)
   # get '/products', to: 'products#index' #index muestra un conjunto de productos
   # get '/products/:id', to: 'products#show', as: :product  #show muetra un producto especifico
   # # cuando alguien vaya a /products, va a ir a un controlados (to:) y ese controlador en este caso products va a ir a un metodo #index (dentro de este metodo vamos a tener la logica para devolver todos los productos.)
   # get '/products/:id/edit', to: 'products#edit', as: :edit_product

   resources :products, path: '/'
end


#localhost:3000/rails/info/routes (muestra todas las rutas)

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class

end

app/models/category.rb
class Category < ApplicationRecord
end

app/models/product.rb
class Product < ApplicationRecord
  has_one_attached :photo
  
  validates:title, presence:true
  validates:description, presence:true
  validates:price, presence:true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
  around_action :switch_locale

  def switch_locale(&action)
    I18n.with_locale(locale_from_header, &action)
  end

  private

  def locale_from_header
    language = request.env['HTTP_ACCEPT_LANGUAGE']
    # Si no hay valor para HTTP_ACCEPT_LANGUAGE, devolvemos un valor predeterminado (por ejemplo, 'es')
    language.present? ? language.scan(/^[a-z]{2}/).first : 'es'
  end
  
end


#Aqui esta la logica real

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: %i[ show edit update destroy ]

  # GET /categories or /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1 or /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories or /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: "Category was successfully created." }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1 or /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: "Category was successfully updated." }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1 or /categories/1.json
  def destroy
    @category.destroy!

    respond_to do |format|
      format.html { redirect_to categories_path, status: :see_other, notice: "Category was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params(:id))
    end

    # Only allow a list of trusted parameters through.
    def category_params
      params.expect(category: [ :id ])
    end
end

app/controllers/products_controller.rb
#Aca creo el controlador de productsController, el que va a heredar de ApplicationController
class ProductsController < ApplicationController #en AppController esta toda la logica
  
  def index  #creamos el metodo 
    @products = Product.all.with_attached_photo  #hace una sola llamada de Query a la db optimizando el code
  end
  
  def show
    product_id
  end

  def new
    @product = Product.new
  end

  def create
    @product = Product.new(product_params)
    
    if @product.save
      redirect_to products_path, notice: t('.created')
    else
      render :new, status: :unprocessable_entity #renderiza pero solo con la resp. que devuelva al nav cod 422 (cuando no se pudo guardar algo en db)
    end

  end
  
  def edit
    product_id
   
  end
  
  def update
    if product_id.update(product_params)
      redirect_to products_path, notice: t('.updated')
    else
      render :edit, status: :unprocessable_entity #renderiza pero solo con la resp. que
    end
  end

  def destroy
    product_id.destroy

    redirect_to products_path, notice: t('.delete'), status: :see_other # status 303 enlaza a un enlace inexistente

  end

  private

  def product_params
    params.require(:product).permit(:title, :price, :description, :photo)
  end
  
  def product_id
    @product = Product.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_category.html.erb
<div id="<%= dom_id category %>">
  <p>
    <strong>Name:</strong>
    <%= category.name %>
  </p>

  <p>
    <strong>:</strong>
    <%= category. %>
  </p>

</div>

app/views/categories/_form.html.erb
<%= form_with(model: category) do |form| %>
  <% if category.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
        <% category.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :, style: "display: block" %>
    <%= form.text_field : %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<% content_for :title, "Editing category" %>

<h1>Editing category</h1>

<%= render "form", category: @category %>

<br>

<div>
  <%= link_to "Show this category", @category %> |
  <%= link_to "Back to categories", categories_path %>
</div>

app/views/categories/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Categories" %>

<h1>Categories</h1>

<div id="categories">
  <% @categories.each do |category| %>
    <%= render category %>
    <p>
      <%= link_to "Show this category", category %>
    </p>
  <% end %>
</div>

<%= link_to "New category", new_category_path %>

app/views/categories/new.html.erb
<% content_for :title, "New category" %>

<h1>New category</h1>

<%= render "form", category: @category %>

<br>

<div>
  <%= link_to "Back to categories", categories_path %>
</div>

app/views/categories/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @category %>

<div>
  <%= link_to "Edit this category", edit_category_path(@category) %> |
  <%= link_to "Back to categories", categories_path %>

  <%= button_to "Destroy this category", @category, method: :delete %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Pagina de ventas" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render 'shared/flash'%>
    <%= render 'shared/header'%>
    <%= yield %>
  </body>
</html>

app/views/products/_form.html.erb
<%= form_with model: @product do |form| %>
  <% @product.errors.full_messages.each do |error| %>
    <div style="color:red">
      <%= error %>
    </div>
    <br>
  <% end %>

  <div>
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :description  %>
    <%= form.text_area :description %>
  </div>

  <div>
    <%= form.label :price %> <!-- Agregado t() para price -->
    <%= form.number_field :price %>
  </div>

  <div>
    <%= form.label :photo %>
    <%= form.file_field :photo %>
  </div>

  <%= form.submit t('products.submit') %>
<% end %>

app/views/products/_product.html.erb
<h3>Id del producto: <%= product.id%></h3>
   <%= image_tag product.photo, width: 150 if product.photo.attached? %> 
   <%= link_to product_path(product.id), class: 'product' do %>
<h2><%= product.title %></h2>
   <% end %>
   
<h3><%= t('shared._product.value')%><%= product.price%></h3>
<hr>

app/views/products/edit.html.erb
<h2><%= t('.title')%></h2>
<%# En la linea2 usamos t() que seria el metodo traductor con el . genera rutas relativas %>
<%# En la linea 6 Creamos un formulario, y lo traemos de un parse _ DRY (para no repetir codigo)%>

<%= render 'form' %>

app/views/products/index.html.erb
<h2><%= t('.title')%></h2>



<%= render partial: 'product', collection: @products %>

app/views/products/new.html.erb
<h2><%= t('.title')%></h2>

<%= render 'form' %>

app/views/products/show.html.erb
<h2><%= t('.chosen_product')%> </h2>
<p class='title'><%= @product.title %></p>
<%= image_tag @product.photo, width: 300 if @product.photo.attached? %> 
<%# Aqui arriba mostramos la foto que tenemos guardada %>
<h3><%= t('.description')%></h3>
<hr>
<p class='description'><%= @product.description %></p>
<hr>

<%= link_to t('.edit_product'), edit_product_path(@product)%>
<%= link_to t('.delete_product'), product_path(@product), data:{
    turbo_method: :delete,
    turbo_confirm: t('common.confirm')
    # Usamos common porque no le queremos dar un scope especifico, asi lo podemos usar en otro lado
}%> 
<%# lo que hacemos con turbo_method es sobre escribir el metodo get que trae por default al method requerido %>



app/views/shared/_flash.html.erb
<%= notice %>
<%= alert %>

app/views/shared/_header.html.erb
<%# todos los partials van con _ al principio y aqui va lo que quiera renderizar en todas las paginas%>
<%= link_to products_path do%>
<h1><%= t('shared._header.title')%></h1>
<% end %>

<%= link_to t('shared._header.newProduct') , new_product_path%>